# Array Manipulation 

## Changing Array Shape 

In [5]:
import numpy as np

# Create a 1D array with values from 0 to 8
a = np.arange(9)

# Print the original 1D array
print("Original Array:")
print(a)
print()

# Reshape the 1D array into a 2D array with 3 rows and 3 columns
b = a.reshape(3, 3)

# Print the reshaped 2D array
print("Modified Array:")
print(b)

Origanal Array:
[0 1 2 3 4 5 6 7 8]

Modified Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Flatten the 2D array 'b' into a 1D array (row-wise, default order)
print(b.flatten())

# Flatten the 2D array 'b' into a 1D array (column-wise, specified by order="F")
print(b.flatten(order="F"))

[0 1 2 3 4 5 6 7 8]
[0 3 6 1 4 7 2 5 8]


In [9]:
# Create a 1D array with values from 0 to 11 and reshape it into a 2D array with 4 rows and 3 columns
a = np.arange(12).reshape(4, 3)

# Display the reshaped 2D array 'a'
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.transpose( ) :

In [11]:
# Transpose the 2D array 'a', swapping its rows and columns
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

 # Numpy Arithmetic Operations :

In [15]:
# Create a 1D array with values from 0 to 8 and reshape it into a 3x3 2D array
a = np.arange(9).reshape(3, 3)

# Create a 1D array with three elements, each having the value 10
b = np.array([10, 10, 10])

In [16]:
# Add the 1D array 'b' to each row of the 2D array 'a' (broadcasting occurs here)
np.add(a, b)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [17]:
# Subtract the 1D array 'b' from each row of the 2D array 'a' (broadcasting occurs here)
np.subtract(a, b)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [18]:
# Multiply each row of the 2D array 'a' by the corresponding element in the 1D array 'b' (broadcasting occurs here)
np.multiply(a, b)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [19]:
np.divide(a,b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

# Slicing :

In [20]:
a = np.arange(20)

In [24]:
print(a[:4])
print(a[4:])
print(a[5])

s = slice(2,12,3)
print(a[s])

[0 1 2 3]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
5
[ 2  5  8 11]
