# Iterating Over Array :

In [1]:
import numpy as np

In [2]:
# Create a 3x3 2D array with values from 0 to 40, with a step of 5
a = np.arange(0, 45, 5).reshape(3, 3)

# Print the original array
print("Original Array:")
print(a)

# Iterate through the array in row-major (C-style) order
print("By Row Major (C-order):")
for i in np.nditer(a, order="C"):
    print(i)

# Iterate through the array in column-major (Fortran-style) order
print("By Column Major (F-order):")
for i in np.nditer(a, order="F"):
    print(i)

Original Array:
[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
By Row Major (C-order):
0
5
10
15
20
25
30
35
40
By Column Major (F-order):
0
15
30
5
20
35
10
25
40


# Joining Arrays :

In [3]:
# Create the first 2D array
a = np.array([[1, 2], [3, 4]])

# Print the first array
print("1st Array")
print(a)

# Create the second 2D array
b = np.array([[5, 6], [7, 8]])

# Print the second array
print("2nd Array")
print(b)

# Concatenate the arrays along axis 0 (vertically, row-wise)
print("Joining arrays along axis 0")
print(np.concatenate((a, b), axis=0))

# Concatenate the arrays along axis 1 (horizontally, column-wise)
print("Joining arrays along axis 1")
print(np.concatenate((a, b), axis=1))

1st Array
[[1 2]
 [3 4]]
2nd Array
[[5 6]
 [7 8]]
Joining arrays along axis 0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Joining arrays along axis 1
[[1 2 5 6]
 [3 4 7 8]]


# Splitting Array :

In [4]:
# Create a 1D array with values from 0 to 8
a = np.arange(9)
print(a)

# Split the array into 3 equal parts
print(np.split(a, 3))  # Splits after every 3 elements

# Split the array at specific indices [4, 5, 7], resulting in segments (0-4), (4-5), (5-7), (7-end)
print(np.split(a, [4, 5, 7]))  # Splits at 0-4, 4-5, 5-7, 7-end

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4]), array([5, 6]), array([7, 8])]


# Resizing An Array

In [5]:
# Create a 2D array 'a' with shape (2, 3)
a = np.array([[1, 2, 3], [4, 5, 6]])
print(f"a\n{a}\nshape:{a.shape}")

# Resize the array 'a' to a new shape (3, 2), elements will be repeated if necessary
b = np.resize(a, (3, 2))
print(f"b\n{b}\nshape:{b.shape}")

a
[[1 2 3]
 [4 5 6]]
shape:(2, 3)
b
[[1 2]
 [3 4]
 [5 6]]
shape:(3, 2)


In [6]:
# Resize the array 'a' to a new shape (3, 3), elements will be repeated to fill the new size
c = np.resize(a, (3, 3))
print(f"c\n{c}\nshape:{c.shape}")  # It starts repeating the elements to match the new shape

c
[[1 2 3]
 [4 5 6]
 [1 2 3]]
shape:(3, 3)


# Histogram :

In [ ]:
from matplotlib import pyplot as plt

# Create a 1D array with the given values
a = np.array([20, 87, 4, 40, 53, 74, 56, 51, 11, 20, 40, 15, 79, 25, 27])

# Create a histogram with specified bins
plt.hist(a, bins=[0, 20, 40, 60, 80, 100])

# Add a title to the histogram
plt.title("Histogram")

# Display the plot
plt.show()

# Other Useful Functions :

In [38]:
# Generate 5 equally spaced values between 0 and 10 (both inclusive)
a = np.linspace(0, 10, 5)

# Print the array of generated values
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [39]:
# Create a 2D array 'a'
a = np.array([[1, 2, 3], [4, 5, 6]])

# Sum the elements along axis 0 (column-wise sum)
print(a.sum(axis=0))

# Sum the elements along axis 1 (row-wise sum)
print(a.sum(axis=1))

[5 7 9]
[ 6 15]


In [40]:
# Compute the square root of each element in the array 'a'
print(np.sqrt(a))
array([[1,2,3],[4,5,6]])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [41]:
# Compute the base-10 logarithm of each element in the array 'a'
print(np.log10(a))

# Compute the base-2 logarithm of each element in the array 'a'
print(np.log2(a))


[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]
