In [1]:
import numpy as np 

# Creating arrays using **np.array()** :
 

In [2]:
import numpy as np  # Importing the numpy library for numerical operations

# Create a NumPy array with the elements 3, 6, 3, and 4
arr = np.array([3, 6, 3, 4])

# Print the entire array
print(arr)

# Access and display the element at index 1 (second element) of the array
print(arr[1])


[3 6 3 4]
6


In [3]:
# Create a 2D NumPy array with two rows and three columns
arr2 = np.array([[1, 2, 3], [7, 8, 9]])

# Print the entire 2D array
print(arr2)

# Access and display the element at row index 1 and column index 0 (value 7)
arr2[1, 0]


[[1 2 3]
 [7 8 9]]


np.int64(7)

# Basic operations :

In [4]:
# Print the shape (dimensions) of the 1D array 'arr'
print(arr.shape)

# Print the shape (dimensions) of the 2D array 'arr2'
print(arr2.shape)

# Print the data type of the elements in the 1D array 'arr'
print(arr.dtype)

# Print the data type of the elements in the 2D array 'arr2'
print(arr2.dtype)

# Print the number of dimensions of the 1D array 'arr'
print(arr.ndim)

# Print the number of dimensions of the 2D array 'arr2'
print(arr2.ndim)

(4,)
(2, 3)
int64
int64
1
2


In [5]:
# Create a 2D array of zeros with 3 rows and 4 columns
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# Create a 2D array of ones with 3 rows and 4 columns
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# Create a 1D array with values ranging from 0 to 4 (exclusive of 5)
np.arange(5)

# Create a 1D array with values starting from 5 up to 60 (exclusive), with a step of 5
np.arange(5, 60, 5)

# Create a 1D array with values starting from 30 down to 5 (exclusive), decrementing by 2
np.arange(30, 5, -2)

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6])

# Numpy String Functions :

In [8]:
# Concatenate corresponding elements of two arrays of strings
np.char.add(["Hello ", "Hi "], ["ABC", "XYZ"])

array(['Hello ABC', 'Hi XYZ'], dtype='<U9')

In [9]:
# Center-align the string "Thank You" within a string of length 30, filling the extra spaces with "-"
np.char.center("Thank You", 30, fillchar="-")

array('----------Thank You-----------', dtype='<U30')

In [10]:
# Capitalize the first letter of the string "hello world"
np.char.capitalize("hello world")

array('Hello world', dtype='<U11')

In [11]:
# Capitalize the first letter of each word in the string "sup what is up"
np.char.title("sup what is up")

array('Sup What Is Up', dtype='<U14')

In [12]:
# Convert all characters in the array ["HELLO", 'WORLD'] to lowercase
np.char.lower(["HELLO", 'WORLD'])

# Convert all characters in the string "HELLO" to lowercase
np.char.lower("HELLO")

array('hello', dtype='<U5')

In [13]:
# Convert all characters in the array ["hello", 'world'] to uppercase
np.char.upper(["hello", 'world'])

# Convert all characters in the string "hello" to uppercase
np.char.upper("hello")

array('HELLO', dtype='<U5')

In [14]:
# Split the string "How's it going?" into a list of words based on spaces
print(np.char.split("How's it going?"))

["How's", 'it', 'going?']


In [15]:
# Split the string "How's it\ngoing?" into a list of lines at newline characters
print(np.char.splitlines("How's it\ngoing?"))

["How's it", 'going?']


In [16]:
# Remove the character 'a' from the beginning and end of each string in the array
print(np.char.strip(["admin", "amount,", "array"], "a"))

['dmin' 'mount,' 'rray']


In [17]:
# Join the elements of the array ["dmy", "ymd"] with ":" and "-" respectively
print(np.char.join([":", "-"], ["dmy", "ymd"]))

['d:m:y' 'y-m-d']


In [18]:
# Replace the substring "is" with "was" in the string "He is a good dancer"
print(np.char.replace("He is a good dancer", "is", "was"))

He was a good dancer
